name: room_reservation_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  provider: ^6.0.2
  flutter_secure_storage: ^9.2.2
  cupertino_icons: ^1.0.8
  jwt_decode: ^0.3.1
  font_awesome_flutter: ^10.7.0
  flutter_timetable: ^1.1.6 # For timeline room availability
  flutter_datetime_picker_plus: ^2.2.0
  table_calendar: ^3.1.2
  syncfusion_flutter_calendar: ^27.1.52

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/login_logo.png
